### ISSUE TITLE
Distributor Info call - Missing Hash

### ISSUE THREAD

**Issue by Serenata-Justin** [51Degrees/device-detection-dotnet#8]
When calling /info to retrieve the product information it sometimes happens that the hash field is empty. Admittedly this only happens intermittently during our automated builds.

This issue may be related to #7 .

**Comment by ben51degrees** [comment]
@Serenata-Justin I believe this was solved as part of some work done on the distributor. Could you confirm whether or not this is still an issue?:
Thanks

**Comment by Tracy51D** [comment]
@Serenata-Justin - In order to ensure timely resolution and manage our resources effectively, we will be closing this issue today.
Should you require any further assistance or if there are any updates on your end, we are here to help. You can simply reopen the ticket or contact us directly and we'll be more than happy to assist you.
